---
- hosts: all
  sudo: yes
  sudo_user: vagrant
  tasks:
    - apt: update_cache=yes
      sudo_user: root
    - name: Install all apt-get packages
      apt: name={{ item }} state=latest
      sudo_user: root
      with_items:
        - git-core
        - libxft-dev
        - libxslt-dev
        - libxml2-dev
        - mysql-server
        - libcurl4-openssl-dev
        - libmysqlclient-dev
        - libpq-dev
        - libbz2-dev
        - libexpat-dev
        - libncurses-dev
        - build-essential
        - curl
        - m4
        - texinfo
        - zlib1g-dev
        - default-jre

    - name: Get RVM gpg key
      shell: "gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3"

    - name: Install RVM
      shell: curl -sSL https://get.rvm.io | bash -s stable creates="~/.rvm"
      args:
        executable: /bin/bash

    - name: Source RVM
      shell: "source /home/vagrant/.rvm/scripts/rvm && rvm rvmrc trust /vagrant/.rvmrc"
      args:
        executable: /bin/bash

    - name: Install ruby
      shell: "source ~/.bash_profile && rvm install 1.9.3"
      args:
        executable: /bin/bash

    - name: Install bundler
      shell: "source ~/.bash_profile && rvm all do gem install bundler"
      args:
        executable: /bin/bash

    - name: Install linuxbrew
      shell: "ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install | sed '/wait_for_user if STDIN.tty/d')\""
      args:
        executable: /bin/bash
        creates: "/home/vagrant/.linuxbrew/"

    - name: Put linuxbrew in bashrc
      lineinfile: create=yes line="export PATH=\"$HOME/.linuxbrew/bin:$PATH\"" insertafter=EOF dest=~/.bash_profile

    - name: Install redis
      shell: "source ~/.bash_profile && ~/.linuxbrew/bin/brew install redis "
      args:
        executable: /bin/bash

    - name: cd to /vagrant in bash profile
      lineinfile:
      args:
        dest: /home/vagrant/.bash_profile
        line: "cd /vagrant"

    - name: Bundle install
      shell: "source ~/.bash_profile && bundle install"
      args:
        executable: /bin/bash
        chdir: "/vagrant"
